<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dockerfiledsl" nsURI="http://www.s5.com/mde/dockerfiledsl" nsPrefix="dockerfiledsl">
  <eClassifiers xsi:type="ecore:EClass" name="HEALTHCHECK" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" eType="#//Option"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmd" eType="#//CMD" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADD" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Src"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dest" lowerBound="1" eType="#//Dest"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checksum" lowerBound="1"
        eType="#//Checksum" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//Usr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//Group"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SHELL" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmd" eType="#//ExecForm"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchellForm" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartPeriod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FROM" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="platfom" eType="#//Platform"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" lowerBound="1" eType="#//Image"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CMD" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COPY" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Src"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dest" lowerBound="1" eType="#//Dest"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//Usr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//Group"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WORKDIR" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" lowerBound="1" eType="#//Path"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Signals">
    <eLiterals name="SIGHUP" value="1"/>
    <eLiterals name="SIGINT" value="2"/>
    <eLiterals name="SIGQUIT" value="3"/>
    <eLiterals name="SIGILL" value="4"/>
    <eLiterals name="SIGTRAP" value="5"/>
    <eLiterals name="SIGABRT" value="6"/>
    <eLiterals name="SIGBUS" value="7"/>
    <eLiterals name="SIGFPE" value="8"/>
    <eLiterals name="SIGKILL" value="9"/>
    <eLiterals name="SIGUSR1" value="10"/>
    <eLiterals name="SIGSEGV" value="11"/>
    <eLiterals name="SIGUSR2" value="12"/>
    <eLiterals name="SIGPIPE" value="13"/>
    <eLiterals name="SIGALRM" value="14"/>
    <eLiterals name="SIGTERM" value="15"/>
    <eLiterals name="SIGSTKFLT" value="16"/>
    <eLiterals name="SIGCHLD" value="17"/>
    <eLiterals name="SIGCONT" value="18"/>
    <eLiterals name="SIGSTOP" value="19"/>
    <eLiterals name="SIGTSTP" value="20"/>
    <eLiterals name="SIGTTIN" value="21"/>
    <eLiterals name="SIGTTOU" value="22"/>
    <eLiterals name="SIGURG" value="23"/>
    <eLiterals name="SIGXCPU" value="24"/>
    <eLiterals name="SIGXFSZ" value="25"/>
    <eLiterals name="SIGVTALRM" value="26"/>
    <eLiterals name="SIGPROF" value="27"/>
    <eLiterals name="SIGWINCH" value="28"/>
    <eLiterals name="SIGIO" value="29"/>
    <eLiterals name="SIGPWR" value="30"/>
    <eLiterals name="SIGSYS" value="31"/>
    <eLiterals name="SIGRTMIN" value="34"/>
    <eLiterals name="SIGRTMAX" value="64"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="STOPSIGNAL" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
        eType="#//Signal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//Path"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//Key"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="USER" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//Usr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//Group"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Src" eSuperTypes="#//Path"/>
  <eClassifiers xsi:type="ecore:EClass" name="Path">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ENV" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyvalues" lowerBound="1"
        upperBound="-1" eType="#//KeyValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sig" lowerBound="1" eType="#//Signals"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ONBUILD" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Retries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Checksum">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VOLUME" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" upperBound="-1"
        eType="#//Data" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Protocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecForm" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="args" lowerBound="2" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LABEL" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyvalues" lowerBound="1"
        upperBound="-1" eType="#//KeyValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Name">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EXPOSE" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="#//Port"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" eType="#//Protocol"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RUN" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ENTRYPOINT" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Key">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tag" eType="#//Tag" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ARG" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//Name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Platform">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dest" eSuperTypes="#//Path"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timeout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dockerfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interval" eType="#//Interval"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeout" eType="#//Timeout"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startperiod" eType="#//StartPeriod"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="retries" eType="#//Retries"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Main">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dockerfile" lowerBound="1"
        eType="#//Dockerfile" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
